#include <Lux/Core/PlatformMacros.hpp>
#include <catch2/catch_test_macros.hpp>

TEST_CASE("PlatformMacros", "[Core]")
{
	SECTION("compiler")
	{
#if LUX_COMPILER(CLANG)
		STATIC_CHECK(LUX_COMPILER(CLANG));
		STATIC_CHECK_FALSE(LUX_COMPILER(GCC));
		STATIC_CHECK_FALSE(LUX_COMPILER(MSVC));
#endif

#if LUX_COMPILER(GCC)
		STATIC_CHECK_FALSE(LUX_COMPILER(CLANG));
		STATIC_CHECK(LUX_COMPILER(GCC));
		STATIC_CHECK_FALSE(LUX_COMPILER(MSVC));
#endif

#if LUX_COMPILER(MSVC)
		STATIC_CHECK_FALSE(LUX_COMPILER(CLANG));
		STATIC_CHECK_FALSE(LUX_COMPILER(GCC));
		STATIC_CHECK(LUX_COMPILER(MSVC));
#endif
	}

	SECTION("os")
	{
#if LUX_OS(WINDOWS)
		STATIC_CHECK(LUX_OS(WINDOWS));
		STATIC_CHECK_FALSE(LUX_OS(LINUX));
		STATIC_CHECK_FALSE(LUX_OS(MAC));
#endif

#if LUX_OS(LINUX)
		STATIC_CHECK_FALSE(LUX_OS(WINDOWS));
		STATIC_CHECK(LUX_OS(LINUX));
		STATIC_CHECK_FALSE(LUX_OS(MAC));
#endif

#if LUX_OS(MAC)
		STATIC_CHECK_FALSE(LUX_OS(WINDOWS));
		STATIC_CHECK_FALSE(LUX_OS(LINUX));
		STATIC_CHECK(LUX_OS(MAC));
#endif
	}

	SECTION("cpp")
	{
		STATIC_CHECK(LUX_CPP(20));
	}
}
